### ISSUE TITLE
Screenshot loading spinner

### ISSUE THREAD

**Issue by jayaddison** [TommyScribble/feedback-popup#3]
Taking a screenshot can take a little while depending on the contents of the page and the network conditions of the client.

It could be useful to display a spinner or progress indicator in the screenshot preview area while a screenshot is being generated.

**Comment by TommyScribble** [comment]
Thanks for the feedback @jayaddison . 
A spinner has been added whilst the screen shot is being gathered.

**Comment by jayaddison** [comment]
Brilliant, thanks! :)
